### List all available tools
GET https://yoursite.com/neosidekick/lawnmower/tools/list
Content-Type: application/json
Authorization: Bearer here-comes-your-bearer-token

{}


### Ping
POST https://yoursite.com/neosidekick/lawnmower/tools/call
Content-Type: application/json
Authorization: Bearer here-comes-your-bearer-token

{
  "name": "Ping",
  "arguments": {
    "param1": "Hello",
    "param2": "World"
  }
}

### Create a new workspace
POST https://yoursite.com/neosidekick/lawnmower/tools/call
Content-Type: application/json
Authorization: Bearer here-comes-your-bearer-token

{
  "name": "CreateWorkspace",
  "arguments": {
    "workspaceName": "my-funny-workspace"
  }
}

### Publish and delete a workspace
POST https://yoursite.com/neosidekick/lawnmower/tools/call
Content-Type: application/json
Authorization: Bearer here-comes-your-bearer-token

{
  "name": "PublishAndDeleteWorkspace",
  "arguments": {
    "workspaceName": "my-funny-workspace"
  }
}

### Discard and delete a workspace
POST https://yoursite.com/neosidekick/lawnmower/tools/call
Content-Type: application/json
Authorization: Bearer here-comes-your-bearer-token

{
  "name": "DiscardAndDeleteWorkspace",
  "arguments": {
    "workspaceName": "my-funny-workspace"
  }
}

### Update node properties
POST https://yoursite.com/neosidekick/lawnmower/tools/call
Content-Type: application/json
Authorization: Bearer here-comes-your-bearer-token

{
  "name": "UpdateNodeProperties",
  "arguments": {
    "nodeContextPath": {
      "nodePath": "/sites/site/main/node-blj8xfx5l21m9",
      "workspaceName": "my-funny-workspace",
      "dimensions": {
          "language": [
            "en_US"
          ]
      }
    },
    "updatedProperties": {
      "text": "<p>foobar3</p>"
    }
  }
}

### Search in nodes
POST https://yoursite.com/neosidekick/lawnmower/tools/call
Content-Type: application/json
Authorization: Bearer here-comes-your-bearer-token

{
  "name": "SearchInNodes",
  "arguments": {
    "term": "John Doe"
  }
}

### Get the sitemap
POST https://yoursite.com/neosidekick/lawnmower/tools/call
Content-Type: application/json
Authorization: Bearer 4FGl4St6UIK6lsFi3iliZrB6dv8Sbk47IitEuusUs1PV9snss0MkAKOiYnVNGt1y

{
  "name": "Sitemap",
  "arguments": {
    "dimension": {
      "language": ["en"]
    }
  }
}
